// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDoWUC9mqOkE4cSQi3psRrP5XSGwONoNJ8',
    appId: '1:553575112331:web:a48a348166d91b23c27e8e',
    messagingSenderId: '553575112331',
    projectId: 'classroom-22f02',
    authDomain: 'classroom-22f02.firebaseapp.com',
    storageBucket: 'classroom-22f02.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDX-hj71zaplIcS16bpz8Ksx7ftvJn3hwA',
    appId: '1:553575112331:android:0b2006f1d8c7315bc27e8e',
    messagingSenderId: '553575112331',
    projectId: 'classroom-22f02',
    storageBucket: 'classroom-22f02.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC4-6uHuIW-QSXzrF448Cjelh48fK_RbYU',
    appId: '1:553575112331:ios:a83e9907cd77d050c27e8e',
    messagingSenderId: '553575112331',
    projectId: 'classroom-22f02',
    storageBucket: 'classroom-22f02.appspot.com',
    iosBundleId: 'com.example.classroom',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC4-6uHuIW-QSXzrF448Cjelh48fK_RbYU',
    appId: '1:553575112331:ios:a83e9907cd77d050c27e8e',
    messagingSenderId: '553575112331',
    projectId: 'classroom-22f02',
    storageBucket: 'classroom-22f02.appspot.com',
    iosBundleId: 'com.example.classroom',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDoWUC9mqOkE4cSQi3psRrP5XSGwONoNJ8',
    appId: '1:553575112331:web:d18e79d046eaa2d3c27e8e',
    messagingSenderId: '553575112331',
    projectId: 'classroom-22f02',
    authDomain: 'classroom-22f02.firebaseapp.com',
    storageBucket: 'classroom-22f02.appspot.com',
  );
}
